export const products = [
  { id: 1, name: "Smartphone", imageUrl: "imag.jpg", price: 20 },
  { id: 2, name: "Running Shoes", imageUrl: "imag2.jpg", price: 25 },
  { id: 3, name: "Coffee Maker", imageUrl: "imag.jpg", price: 20 },
  { id: 4, name: "Backpack", imageUrl: "imag2.jpg", price: 25 },
  { id: 5, name: "Headphones", imageUrl: "imag.jpg", price: 20 },
  { id: 6, name: "Sunglasses", imageUrl: "imag2.jpg", price: 25 },
  { id: 7, name: "Watch", imageUrl: "imag.jpg", price: 20 },
  { id: 8, name: "Digital Camera", imageUrl: "imag2.jpg", price: 25 },
  { id: 9, name: "Yoga Mat", imageUrl: "imag.jpg", price: 20 },
  { id: 10, name: "Laptop", imageUrl: "imag2.jpg", price: 25 },
  { id: 11, name: "Television", imageUrl: "imag.jpg", price: 20 },
  { id: 12, name: "Gaming Console", imageUrl: "imag2.jpg", price: 25 },
  { id: 13, name: "Blender", imageUrl: "imag.jpg", price: 20 },
  { id: 14, name: "Vacuum Cleaner", imageUrl: "imag2.jpg", price: 25 },
  { id: 15, name: "Running Jacket", imageUrl: "imag.jpg", price: 20 },
  { id: 16, name: "Digital Scale", imageUrl: "imag2.jpg", price: 25 },
  { id: 17, name: "Hair Dryer", imageUrl: "imag.jpg", price: 20 },
  { id: 18, name: "Portable Charger", imageUrl: "imag2.jpg", price: 25 },
];
