export const products = [
  { id: 1, name: "Product1", imageUrl: "imag.jpg", price: 20 },
  { id: 2, name: "Product2", imageUrl: "imag2.jpg", price: 25 },
  { id: 3, name: "Product1", imageUrl: "imag.jpg", price: 20 },
  { id: 4, name: "Product2", imageUrl: "imag2.jpg", price: 25 },
  { id: 5, name: "Product1", imageUrl: "imag.jpg", price: 20 },
  { id: 6, name: "Product2", imageUrl: "imag2.jpg", price: 25 },
  { id: 7, name: "Product1", imageUrl: "imag.jpg", price: 20 },
  { id: 8, name: "Product2", imageUrl: "imag2.jpg", price: 25 },
  { id: 9, name: "Product1", imageUrl: "imag.jpg", price: 20 },
  { id: 10, name: "Product2", imageUrl: "imag2.jpg", price: 25 },
  { id: 11, name: "Product1", imageUrl: "imag.jpg", price: 20 },
  { id: 12, name: "Product2", imageUrl: "imag2.jpg", price: 25 },
  { id: 13, name: "Product1", imageUrl: "imag.jpg", price: 20 },
  { id: 14, name: "Product2", imageUrl: "imag2.jpg", price: 25 },
  { id: 15, name: "Product1", imageUrl: "imag.jpg", price: 20 },
  { id: 16, name: "Product2", imageUrl: "imag2.jpg", price: 25 },
  { id: 17, name: "Product1", imageUrl: "imag.jpg", price: 20 },
  { id: 18, name: "Product2", imageUrl: "imag2.jpg", price: 25 },
];
